name: Build Image

on: [pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        architecture: [x86_64, aarch64, armhf]
        
        include:
          - architecture: x86_64
            platform: linux/amd64

          - architecture: aarch64
            platform: linux/arm64

          - architecture: armhf
            platform: linux/arm/v7

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build ${{ matrix.architecture }} image
        run: make image TARGET_ARCH=${{ matrix.architecture }} TARGET_PLATFORMS=${{ matrix.platform }}
